// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AccountPasswordChangeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAccountPasswordChangeRequest(buf []byte, offset flatbuffers.UOffsetT) *AccountPasswordChangeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AccountPasswordChangeRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishAccountPasswordChangeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAccountPasswordChangeRequest(buf []byte, offset flatbuffers.UOffsetT) *AccountPasswordChangeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AccountPasswordChangeRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAccountPasswordChangeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AccountPasswordChangeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AccountPasswordChangeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AccountPasswordChangeRequest) CurrentPassword() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AccountPasswordChangeRequest) NewPassword() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AccountPasswordChangeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AccountPasswordChangeRequestAddCurrentPassword(builder *flatbuffers.Builder, currentPassword flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(currentPassword), 0)
}
func AccountPasswordChangeRequestAddNewPassword(builder *flatbuffers.Builder, newPassword flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(newPassword), 0)
}
func AccountPasswordChangeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
