// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ContainerCreateRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsContainerCreateRequest(buf []byte, offset flatbuffers.UOffsetT) *ContainerCreateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ContainerCreateRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishContainerCreateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsContainerCreateRequest(buf []byte, offset flatbuffers.UOffsetT) *ContainerCreateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ContainerCreateRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedContainerCreateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ContainerCreateRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ContainerCreateRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ContainerCreateRequest) Code() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ContainerCreateRequest) MaxCapacity() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ContainerCreateRequest) MutateMaxCapacity(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func ContainerCreateRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ContainerCreateRequestAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(code), 0)
}
func ContainerCreateRequestAddMaxCapacity(builder *flatbuffers.Builder, maxCapacity float64) {
	builder.PrependFloat64Slot(1, maxCapacity, 0.0)
}
func ContainerCreateRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
