// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ContainerSummaryListResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsContainerSummaryListResponse(buf []byte, offset flatbuffers.UOffsetT) *ContainerSummaryListResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ContainerSummaryListResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishContainerSummaryListResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsContainerSummaryListResponse(buf []byte, offset flatbuffers.UOffsetT) *ContainerSummaryListResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ContainerSummaryListResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedContainerSummaryListResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ContainerSummaryListResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ContainerSummaryListResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ContainerSummaryListResponse) Data(obj *ContainerSummaryResponse, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ContainerSummaryListResponse) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ContainerSummaryListResponse) NextCursor() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ContainerSummaryListResponse) Total() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ContainerSummaryListResponse) MutateTotal(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func ContainerSummaryListResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ContainerSummaryListResponseAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func ContainerSummaryListResponseStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ContainerSummaryListResponseAddNextCursor(builder *flatbuffers.Builder, nextCursor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(nextCursor), 0)
}
func ContainerSummaryListResponseAddTotal(builder *flatbuffers.Builder, total int32) {
	builder.PrependInt32Slot(2, total, 0)
}
func ContainerSummaryListResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
