// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ContainerSummaryResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsContainerSummaryResponse(buf []byte, offset flatbuffers.UOffsetT) *ContainerSummaryResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ContainerSummaryResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishContainerSummaryResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsContainerSummaryResponse(buf []byte, offset flatbuffers.UOffsetT) *ContainerSummaryResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ContainerSummaryResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedContainerSummaryResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ContainerSummaryResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ContainerSummaryResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ContainerSummaryResponse) Container(obj *ContainerResponse) *ContainerResponse {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ContainerResponse)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ContainerSummaryResponse) Manifest(obj *CargoManifestItem, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ContainerSummaryResponse) ManifestLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ContainerSummaryResponse) RecentLogs(obj *TelemetryLogItem, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ContainerSummaryResponse) RecentLogsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ContainerSummaryResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ContainerSummaryResponseAddContainer(builder *flatbuffers.Builder, container flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(container), 0)
}
func ContainerSummaryResponseAddManifest(builder *flatbuffers.Builder, manifest flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(manifest), 0)
}
func ContainerSummaryResponseStartManifestVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ContainerSummaryResponseAddRecentLogs(builder *flatbuffers.Builder, recentLogs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(recentLogs), 0)
}
func ContainerSummaryResponseStartRecentLogsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ContainerSummaryResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
