// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ContainerResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsContainerResponse(buf []byte, offset flatbuffers.UOffsetT) *ContainerResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ContainerResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishContainerResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsContainerResponse(buf []byte, offset flatbuffers.UOffsetT) *ContainerResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ContainerResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedContainerResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ContainerResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ContainerResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ContainerResponse) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ContainerResponse) Code() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ContainerResponse) CurrentWeight() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ContainerResponse) MutateCurrentWeight(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func (rcv *ContainerResponse) MaxCapacity() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ContainerResponse) MutateMaxCapacity(n float64) bool {
	return rcv._tab.MutateFloat64Slot(10, n)
}

func (rcv *ContainerResponse) Status() ContainerStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return ContainerStatus(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ContainerResponse) MutateStatus(n ContainerStatus) bool {
	return rcv._tab.MutateByteSlot(12, byte(n))
}

func ContainerResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func ContainerResponseAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func ContainerResponseAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(code), 0)
}
func ContainerResponseAddCurrentWeight(builder *flatbuffers.Builder, currentWeight float64) {
	builder.PrependFloat64Slot(2, currentWeight, 0.0)
}
func ContainerResponseAddMaxCapacity(builder *flatbuffers.Builder, maxCapacity float64) {
	builder.PrependFloat64Slot(3, maxCapacity, 0.0)
}
func ContainerResponseAddStatus(builder *flatbuffers.Builder, status ContainerStatus) {
	builder.PrependByteSlot(4, byte(status), 0)
}
func ContainerResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
