// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type ContainerStatus byte

const (
	ContainerStatusEmpty     ContainerStatus = 0
	ContainerStatusLoading   ContainerStatus = 1
	ContainerStatusSealed    ContainerStatus = 2
	ContainerStatusInTransit ContainerStatus = 3
)

var EnumNamesContainerStatus = map[ContainerStatus]string{
	ContainerStatusEmpty:     "Empty",
	ContainerStatusLoading:   "Loading",
	ContainerStatusSealed:    "Sealed",
	ContainerStatusInTransit: "InTransit",
}

var EnumValuesContainerStatus = map[string]ContainerStatus{
	"Empty":     ContainerStatusEmpty,
	"Loading":   ContainerStatusLoading,
	"Sealed":    ContainerStatusSealed,
	"InTransit": ContainerStatusInTransit,
}

func (v ContainerStatus) String() string {
	if s, ok := EnumNamesContainerStatus[v]; ok {
		return s
	}
	return "ContainerStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
