// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ContainerUpdateRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsContainerUpdateRequest(buf []byte, offset flatbuffers.UOffsetT) *ContainerUpdateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ContainerUpdateRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishContainerUpdateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsContainerUpdateRequest(buf []byte, offset flatbuffers.UOffsetT) *ContainerUpdateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ContainerUpdateRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedContainerUpdateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ContainerUpdateRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ContainerUpdateRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ContainerUpdateRequest) MaxCapacity() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ContainerUpdateRequest) MutateMaxCapacity(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func ContainerUpdateRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ContainerUpdateRequestAddMaxCapacity(builder *flatbuffers.Builder, maxCapacity float64) {
	builder.PrependFloat64Slot(0, maxCapacity, 0.0)
}
func ContainerUpdateRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
