// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LoadItemRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsLoadItemRequest(buf []byte, offset flatbuffers.UOffsetT) *LoadItemRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LoadItemRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishLoadItemRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLoadItemRequest(buf []byte, offset flatbuffers.UOffsetT) *LoadItemRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LoadItemRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLoadItemRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LoadItemRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LoadItemRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LoadItemRequest) ContainerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LoadItemRequest) ProductId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LoadItemRequest) Quantity() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *LoadItemRequest) MutateQuantity(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func LoadItemRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func LoadItemRequestAddContainerId(builder *flatbuffers.Builder, containerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(containerId), 0)
}
func LoadItemRequestAddProductId(builder *flatbuffers.Builder, productId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(productId), 0)
}
func LoadItemRequestAddQuantity(builder *flatbuffers.Builder, quantity float64) {
	builder.PrependFloat64Slot(2, quantity, 0.0)
}
func LoadItemRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
