// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetadataItemResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsMetadataItemResponse(buf []byte, offset flatbuffers.UOffsetT) *MetadataItemResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetadataItemResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetadataItemResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetadataItemResponse(buf []byte, offset flatbuffers.UOffsetT) *MetadataItemResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetadataItemResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetadataItemResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetadataItemResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetadataItemResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetadataItemResponse) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetadataItemResponse) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *MetadataItemResponse) Slug() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetadataItemResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetadataItemResponseAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func MetadataItemResponseAddSlug(builder *flatbuffers.Builder, slug flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(slug), 0)
}
func MetadataItemResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
