// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetricsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsMetricsResponse(buf []byte, offset flatbuffers.UOffsetT) *MetricsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetricsResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetricsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetricsResponse(buf []byte, offset flatbuffers.UOffsetT) *MetricsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetricsResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetricsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetricsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetricsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetricsResponse) ActiveContainers() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetricsResponse) MutateActiveContainers(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *MetricsResponse) TotalContainers() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetricsResponse) MutateTotalContainers(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *MetricsResponse) YardLoad() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *MetricsResponse) MutateYardLoad(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func (rcv *MetricsResponse) RegisteredProducts() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetricsResponse) MutateRegisteredProducts(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *MetricsResponse) OccupancyDivision(obj *OccupancyDivision) *OccupancyDivision {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OccupancyDivision)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MetricsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MetricsResponseAddActiveContainers(builder *flatbuffers.Builder, activeContainers int32) {
	builder.PrependInt32Slot(0, activeContainers, 0)
}
func MetricsResponseAddTotalContainers(builder *flatbuffers.Builder, totalContainers int32) {
	builder.PrependInt32Slot(1, totalContainers, 0)
}
func MetricsResponseAddYardLoad(builder *flatbuffers.Builder, yardLoad float64) {
	builder.PrependFloat64Slot(2, yardLoad, 0.0)
}
func MetricsResponseAddRegisteredProducts(builder *flatbuffers.Builder, registeredProducts int32) {
	builder.PrependInt32Slot(3, registeredProducts, 0)
}
func MetricsResponseAddOccupancyDivision(builder *flatbuffers.Builder, occupancyDivision flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(occupancyDivision), 0)
}
func MetricsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
