// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OccupancyDivision struct {
	_tab flatbuffers.Table
}

func GetRootAsOccupancyDivision(buf []byte, offset flatbuffers.UOffsetT) *OccupancyDivision {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OccupancyDivision{}
	x.Init(buf, n+offset)
	return x
}

func FinishOccupancyDivisionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOccupancyDivision(buf []byte, offset flatbuffers.UOffsetT) *OccupancyDivision {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OccupancyDivision{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOccupancyDivisionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OccupancyDivision) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OccupancyDivision) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OccupancyDivision) Empty() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OccupancyDivision) MutateEmpty(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *OccupancyDivision) Loading() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OccupancyDivision) MutateLoading(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *OccupancyDivision) Sealed() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OccupancyDivision) MutateSealed(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *OccupancyDivision) InTransit() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OccupancyDivision) MutateInTransit(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func OccupancyDivisionStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func OccupancyDivisionAddEmpty(builder *flatbuffers.Builder, empty int32) {
	builder.PrependInt32Slot(0, empty, 0)
}
func OccupancyDivisionAddLoading(builder *flatbuffers.Builder, loading int32) {
	builder.PrependInt32Slot(1, loading, 0)
}
func OccupancyDivisionAddSealed(builder *flatbuffers.Builder, sealed int32) {
	builder.PrependInt32Slot(2, sealed, 0)
}
func OccupancyDivisionAddInTransit(builder *flatbuffers.Builder, inTransit int32) {
	builder.PrependInt32Slot(3, inTransit, 0)
}
func OccupancyDivisionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
