// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ProductResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsProductResponse(buf []byte, offset flatbuffers.UOffsetT) *ProductResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProductResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishProductResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsProductResponse(buf []byte, offset flatbuffers.UOffsetT) *ProductResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProductResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedProductResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ProductResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProductResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProductResponse) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProductResponse) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProductResponse) Density() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ProductResponse) MutateDensity(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func (rcv *ProductResponse) RiskClass() RiskClass {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return RiskClass(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ProductResponse) MutateRiskClass(n RiskClass) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

func ProductResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ProductResponseAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func ProductResponseAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func ProductResponseAddDensity(builder *flatbuffers.Builder, density float64) {
	builder.PrependFloat64Slot(2, density, 0.0)
}
func ProductResponseAddRiskClass(builder *flatbuffers.Builder, riskClass RiskClass) {
	builder.PrependByteSlot(3, byte(riskClass), 0)
}
func ProductResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
