// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ProductUpdateRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsProductUpdateRequest(buf []byte, offset flatbuffers.UOffsetT) *ProductUpdateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProductUpdateRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishProductUpdateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsProductUpdateRequest(buf []byte, offset flatbuffers.UOffsetT) *ProductUpdateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProductUpdateRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedProductUpdateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ProductUpdateRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProductUpdateRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProductUpdateRequest) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProductUpdateRequest) Density() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ProductUpdateRequest) MutateDensity(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func (rcv *ProductUpdateRequest) RiskClass() RiskClass {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return RiskClass(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ProductUpdateRequest) MutateRiskClass(n RiskClass) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func ProductUpdateRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ProductUpdateRequestAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func ProductUpdateRequestAddDensity(builder *flatbuffers.Builder, density float64) {
	builder.PrependFloat64Slot(1, density, 0.0)
}
func ProductUpdateRequestAddRiskClass(builder *flatbuffers.Builder, riskClass RiskClass) {
	builder.PrependByteSlot(2, byte(riskClass), 0)
}
func ProductUpdateRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
