// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type RiskClass byte

const (
	RiskClassClass1Explosives           RiskClass = 0
	RiskClassClass2Gases                RiskClass = 1
	RiskClassClass3FlammableLiquids     RiskClass = 2
	RiskClassClass4FlammableSolids      RiskClass = 3
	RiskClassClass5OxidizingSubstances  RiskClass = 4
	RiskClassClass6ToxicSubstances      RiskClass = 5
	RiskClassClass7RadioactiveMaterials RiskClass = 6
	RiskClassClass8CorrosiveSubstances  RiskClass = 7
	RiskClassClass9Miscellaneous        RiskClass = 8
	RiskClassNone                       RiskClass = 9
)

var EnumNamesRiskClass = map[RiskClass]string{
	RiskClassClass1Explosives:           "Class1Explosives",
	RiskClassClass2Gases:                "Class2Gases",
	RiskClassClass3FlammableLiquids:     "Class3FlammableLiquids",
	RiskClassClass4FlammableSolids:      "Class4FlammableSolids",
	RiskClassClass5OxidizingSubstances:  "Class5OxidizingSubstances",
	RiskClassClass6ToxicSubstances:      "Class6ToxicSubstances",
	RiskClassClass7RadioactiveMaterials: "Class7RadioactiveMaterials",
	RiskClassClass8CorrosiveSubstances:  "Class8CorrosiveSubstances",
	RiskClassClass9Miscellaneous:        "Class9Miscellaneous",
	RiskClassNone:                       "None",
}

var EnumValuesRiskClass = map[string]RiskClass{
	"Class1Explosives":           RiskClassClass1Explosives,
	"Class2Gases":                RiskClassClass2Gases,
	"Class3FlammableLiquids":     RiskClassClass3FlammableLiquids,
	"Class4FlammableSolids":      RiskClassClass4FlammableSolids,
	"Class5OxidizingSubstances":  RiskClassClass5OxidizingSubstances,
	"Class6ToxicSubstances":      RiskClassClass6ToxicSubstances,
	"Class7RadioactiveMaterials": RiskClassClass7RadioactiveMaterials,
	"Class8CorrosiveSubstances":  RiskClassClass8CorrosiveSubstances,
	"Class9Miscellaneous":        RiskClassClass9Miscellaneous,
	"None":                       RiskClassNone,
}

func (v RiskClass) String() string {
	if s, ok := EnumNamesRiskClass[v]; ok {
		return s
	}
	return "RiskClass(" + strconv.FormatInt(int64(v), 10) + ")"
}
