// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RolePermissionsUpdateRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRolePermissionsUpdateRequest(buf []byte, offset flatbuffers.UOffsetT) *RolePermissionsUpdateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RolePermissionsUpdateRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishRolePermissionsUpdateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRolePermissionsUpdateRequest(buf []byte, offset flatbuffers.UOffsetT) *RolePermissionsUpdateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RolePermissionsUpdateRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRolePermissionsUpdateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RolePermissionsUpdateRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RolePermissionsUpdateRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RolePermissionsUpdateRequest) Permissions(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *RolePermissionsUpdateRequest) PermissionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RolePermissionsUpdateRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RolePermissionsUpdateRequestAddPermissions(builder *flatbuffers.Builder, permissions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(permissions), 0)
}
func RolePermissionsUpdateRequestStartPermissionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RolePermissionsUpdateRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
