// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TelemetryLogItem struct {
	_tab flatbuffers.Table
}

func GetRootAsTelemetryLogItem(buf []byte, offset flatbuffers.UOffsetT) *TelemetryLogItem {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TelemetryLogItem{}
	x.Init(buf, n+offset)
	return x
}

func FinishTelemetryLogItemBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTelemetryLogItem(buf []byte, offset flatbuffers.UOffsetT) *TelemetryLogItem {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TelemetryLogItem{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTelemetryLogItemBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TelemetryLogItem) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TelemetryLogItem) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TelemetryLogItem) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TelemetryLogItem) Event() TelemetryEvent {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return TelemetryEvent(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TelemetryLogItem) MutateEvent(n TelemetryEvent) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *TelemetryLogItem) Description() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TelemetryLogItem) Timestamp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TelemetryLogItemStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func TelemetryLogItemAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func TelemetryLogItemAddEvent(builder *flatbuffers.Builder, event TelemetryEvent) {
	builder.PrependByteSlot(1, byte(event), 0)
}
func TelemetryLogItemAddDescription(builder *flatbuffers.Builder, description flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(description), 0)
}
func TelemetryLogItemAddTimestamp(builder *flatbuffers.Builder, timestamp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(timestamp), 0)
}
func TelemetryLogItemEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
