// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type TelemetryEvent byte

const (
	TelemetryEventLoad   TelemetryEvent = 0
	TelemetryEventUnload TelemetryEvent = 1
)

var EnumNamesTelemetryEvent = map[TelemetryEvent]string{
	TelemetryEventLoad:   "Load",
	TelemetryEventUnload: "Unload",
}

var EnumValuesTelemetryEvent = map[string]TelemetryEvent{
	"Load":   TelemetryEventLoad,
	"Unload": TelemetryEventUnload,
}

func (v TelemetryEvent) String() string {
	if s, ok := EnumNamesTelemetryEvent[v]; ok {
		return s
	}
	return "TelemetryEvent(" + strconv.FormatInt(int64(v), 10) + ")"
}
