// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UnloadItemRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsUnloadItemRequest(buf []byte, offset flatbuffers.UOffsetT) *UnloadItemRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UnloadItemRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishUnloadItemRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUnloadItemRequest(buf []byte, offset flatbuffers.UOffsetT) *UnloadItemRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UnloadItemRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUnloadItemRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UnloadItemRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UnloadItemRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UnloadItemRequest) ContainerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UnloadItemRequest) ProductId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UnloadItemRequest) Quantity() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *UnloadItemRequest) MutateQuantity(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func UnloadItemRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func UnloadItemRequestAddContainerId(builder *flatbuffers.Builder, containerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(containerId), 0)
}
func UnloadItemRequestAddProductId(builder *flatbuffers.Builder, productId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(productId), 0)
}
func UnloadItemRequestAddQuantity(builder *flatbuffers.Builder, quantity float64) {
	builder.PrependFloat64Slot(2, quantity, 0.0)
}
func UnloadItemRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
