// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserAdminPasswordResetRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsUserAdminPasswordResetRequest(buf []byte, offset flatbuffers.UOffsetT) *UserAdminPasswordResetRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserAdminPasswordResetRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishUserAdminPasswordResetRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUserAdminPasswordResetRequest(buf []byte, offset flatbuffers.UOffsetT) *UserAdminPasswordResetRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserAdminPasswordResetRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUserAdminPasswordResetRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UserAdminPasswordResetRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserAdminPasswordResetRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserAdminPasswordResetRequest) NewPassword() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UserAdminPasswordResetRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UserAdminPasswordResetRequestAddNewPassword(builder *flatbuffers.Builder, newPassword flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(newPassword), 0)
}
func UserAdminPasswordResetRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
