// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserRolesUpdateRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsUserRolesUpdateRequest(buf []byte, offset flatbuffers.UOffsetT) *UserRolesUpdateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserRolesUpdateRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishUserRolesUpdateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUserRolesUpdateRequest(buf []byte, offset flatbuffers.UOffsetT) *UserRolesUpdateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserRolesUpdateRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUserRolesUpdateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UserRolesUpdateRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserRolesUpdateRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserRolesUpdateRequest) RoleIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *UserRolesUpdateRequest) RoleIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func UserRolesUpdateRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UserRolesUpdateRequestAddRoleIds(builder *flatbuffers.Builder, roleIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(roleIds), 0)
}
func UserRolesUpdateRequestStartRoleIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func UserRolesUpdateRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
